Pipeline:
  name: foo

GitRepo:
  name: fooGitRepo1
  gitProvider: deepikaGithub
  path: deepikasl/jfrog_pipelines
  branches:
    exclude: 'master'
    include: {{gitBranch}}

artifactoryIntegration: deepikaArt

Image:
  name: fooImage1
  sourceRepository: foo
  autoPull: false

DockerBuild:
  name: foobuild
  dockerImageName: foo
  dockerFileName: foo
  dockerFileLocation: '.'
  dockerImageTag: ${run_number}

DockerPush:
  name: foopush
  targetRepository: foo

BuildInfo:
  autoPublishBuildInfo: true
  name: fooBuildInfo1
